### PR TITLE
Set up tox-conda/pytest

### PR DESCRIPTION
**Pull request by ajjackson**
- Set build-backend so isolated pip install works
- Add pychop as testing dependency
- Configure tox-conda
- Create `__init__.py` files under tests/ so that all tests are found by pytest

We need to use conda to install Mantid and check results against Abins functions. Tox-conda is stuck on tox v3; there is a branch to support v4 but it's not clear if/when this will be finished. But we also might be able to drop the conda component of these tests once we are satisfied with validation against Mantid: it can be replaced with tests against reference values.

Perhaps we don't need the test dependencies at all in pyproject.toml, now this is all defined in tox.ini. But they could be useful for running tests without tox if desired.

### CODE REVIEW

**Comment by ajjackson** [comment]
This is a decent start, the tests seem to be running correctly. Lots are failing, but we expected that.

**Comment by ajjackson** [comment]
There's more work to do on test coverage / legibility / efficiency but this at least gets some CI up and running without too much complexity or runtime. Would be good to fix the failing tests next!

**Comment by RastislavTuranyi** [comment]
The MAPS and MARI integration tests against AbINS that are failing in CI, on my local they are all passing.

The tests seem to be failing due to `NoTransmissionError`, but that case is expected (it should go into the `except` block). The interesting thing is that AbINS is not raising a `LinAlgError` for the invalid combinations of energy and frequency, causing our strategy to fail. Maybe the CI is using a different version of Mantid? Have there been any relevant changes to AbINS that change the behaviour that the tests expect?
```
    try:
        abins._polyfits = {}
        expected = abins.calculate_sigma(frequencies * MEV_TO_WAVENUMBER) * WAVENUMBER_TO_MEV
    except LinAlgError:
        with pytest.raises(NoTransmissionError):
            rf_2d.get_resolution_function('PyChop_fit', chopper_package=setting, e_init=energy, chopper_frequency=chopper_frequency)
    else:
        rf = rf_2d.get_resolution_function('PyChop_fit', chopper_package=setting, e_init=energy,
                                           chopper_frequency=chopper_frequency)
        actual = rf(frequencies)

        assert_allclose(actual, expected, rtol=1e-5)
```

Concerning the failing Lagrange tests, those are due to the issue in AbINS where the cut-off values have a bug in the unit conversion, resulting in the low-energy values being incorrect.

**Comment by ajjackson** [comment]
In Mantid, if I try to call calculate_sigma() at invalid energy/chopper settings I get NaN back; it doesn't raise an error at this point. How do you get the LinAlgError to appear?

(It probably should, this would give better user feedback.)

**Comment by RastislavTuranyi** [comment]
I get this in tests (i.e. `np.polyfit` raising a `LinAlgError`):
```
tests\integration_tests\test_pychop.py:57 (test_against_abins[MAPS_A-ei=50,f=450])
matrix = (50, 450)
abins_rf_2d = (<abins.instruments.pychop.PyChopInstrument object at 0x000001E292EC78E0>, Instrument(name='MAPS', version='MAPS', mod...'tjit': 0.0}, 'S': {'pslit': 0.002899, 'radius': 0.049, 'rho': 1.3, 'tjit': 0.0}}}}}, default_model='PyChop_fit'), 'A')

    @pytest.mark.parametrize('matrix', EF_MATRIX, ids=EF_IDS)
    def test_against_abins(matrix, abins_rf_2d,):
        abins, rf_2d, setting = abins_rf_2d
>       _test_against_abins(abins, rf_2d, setting, matrix)

integration_tests\test_pychop.py:61: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
integration_tests\test_pychop.py:73: in _test_against_abins
    expected = abins.calculate_sigma(frequencies * MEV_TO_WAVENUMBER) * WAVENUMBER_TO_MEV
..\..\..\..\AppData\Local\miniconda3\envs\rfd\Library\scripts\abins\instruments\pychop.py:53: in calculate_sigma
    self._polyfit_resolution()
..\..\..\..\AppData\Local\miniconda3\envs\rfd\Library\scripts\abins\instruments\pychop.py:66: in _polyfit_resolution
    fit = np.polyfit(frequencies_invcm, resolution_sigma * MILLI_EV_TO_WAVENUMBER, order)
..\..\..\..\AppData\Local\miniconda3\envs\rfd\lib\site-packages\numpy\lib\polynomial.py:669: in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
..\..\..\..\AppData\Local\miniconda3\envs\rfd\lib\site-packages\numpy\linalg\linalg.py:2326: in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

err = 'invalid value', flag = 8

    def _raise_linalgerror_lstsq(err, flag):
>       raise LinAlgError("SVD did not converge in Linear Least Squares")
E       numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

..\..\..\..\AppData\Local\miniconda3\envs\rfd\lib\site-packages\numpy\linalg\linalg.py:124: LinAlgError
```

**Comment by RastislavTuranyi** [comment]
Could indeed be a Windows issue (e.g. [this numpy problem caused by a bug in Windows](https://github.com/numpy/numpy/issues/16744), which should be resolved, but there could be something happening again?).

In either case, we could add a check for nans to the `else` statement:

```
    try:
        abins._polyfits = {}
        expected = abins.calculate_sigma(frequencies * MEV_TO_WAVENUMBER) * WAVENUMBER_TO_MEV
    except LinAlgError:
        with pytest.raises(NoTransmissionError):
            rf_2d.get_resolution_function('PyChop_fit', chopper_package=setting, e_init=energy, chopper_frequency=chopper_frequency)
    else:
        if np.any(np.isnan(expected)):
            with pytest.raises(NoTransmissionError):
                rf_2d.get_resolution_function('PyChop_fit', chopper_package=setting, e_init=energy, chopper_frequency=chopper_frequency)
            return

        rf = rf_2d.get_resolution_function('PyChop_fit', chopper_package=setting, e_init=energy,
                                           chopper_frequency=chopper_frequency)
        actual = rf(frequencies)

        assert_allclose(actual, expected, rtol=1e-5)
```

**Comment by ajjackson** [comment]
Yup, on Windows there are only the Lagrange failures so it is taking different paths depending on platform/libraries 😭

**Comment by RastislavTuranyi** [comment]
PyChop issues a warning (`warnings.warn`) when it returns a nan due to no transmission; we could take advantage of that:

```
    abins._polyfits = {}

    with warnings.catch_warnings():
        warnings.filterwarnings('error', message='PyChop: tchop\(\): No transmission.*')
        try:
            expected = abins.calculate_sigma(frequencies * MEV_TO_WAVENUMBER) * WAVENUMBER_TO_MEV
        except Warning:
            with pytest.raises(NoTransmissionError):
                rf_2d.get_resolution_function('PyChop_fit', chopper_package=setting, e_init=energy, chopper_frequency=chopper_frequency)
        else:
            rf = rf_2d.get_resolution_function('PyChop_fit', chopper_package=setting, e_init=energy,
                                               chopper_frequency=chopper_frequency)
            actual = rf(frequencies)

            assert_allclose(actual, expected, rtol=1e-5)
```

**Comment by ajjackson** [comment]
NaN check is working, will give warning a try and see which is nicer

**Comment by ajjackson** [comment]
Warning-based logic looks a bit cleaner to me and seems to work across platforms 👍 

I have set the low-frequency Abins-Lagrange comparison to skip, as we know that one is suspect. Higher frequencies are ok but I needed to slightly loosen the `assert_allclose` tolerance.

I'd still like to see some of these parameter sweeps collapsed into single test cases, this seems useful enough to merge now?

**Pull request merged**
